# Generated by Django 4.1.7 on 2023-03-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField()),
                ('nome', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=9)),
                ('especialidade', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('experiencia', models.CharField(max_length=30)),
                ('crm', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('nome', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=9)),
                ('sintomas', models.CharField(max_length=30)),
                ('doenca_historico_familiar', models.CharField(max_length=30)),
                ('medicacoes_em_uso', models.CharField(max_length=30)),
                ('alergias', models.CharField(max_length=30)),
                ('exames_recentes', models.CharField(max_length=20)),
                ('pressao', models.CharField(max_length=10)),
                ('temperatura', models.CharField(max_length=10)),
                ('frequencia_cardiaca', models.CharField(max_length=10)),
                ('saturacao', models.CharField(max_length=10)),
                ('frequencia_respiratoria', models.CharField(max_length=10)),
            ],
        ),
    ]
