# Generated by Django 4.1.7 on 2023-03-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='doenca_historico_familiar',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='exames_recentes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='frequencia_cardiaca',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='frequencia_respiratoria',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicacoes_em_uso',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pressao',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='saturacao',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='temperatura',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sintomas',
            field=models.CharField(max_length=9),
        ),
    ]
