# Generated by Django 4.1.7 on 2023-03-19 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasapp', '0002_remove_medico_crm_remove_medico_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='crm_medico',
            field=models.CharField(default='123', max_length=10),
        ),
        migrations.AddField(
            model_name='medico',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='medico',
            name='experiencia',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='medico',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='doenca_historico_familiar',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='exames_recentes',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='frequencia_cardiaca',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='frequencia_respiratoria',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicacoes_em_uso',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pressao',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='paciente',
            name='saturacao',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='temperatura',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='medico',
            name='rg',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_consulta',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sintomas',
            field=models.CharField(default='', max_length=30),
        ),
    ]
