# Generated by Django 4.1.7 on 2023-03-19 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasapp', '0003_medico_crm_medico_medico_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
