# Generated by Django 4.1.7 on 2023-03-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasapp', '0004_alter_medico_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medico',
            name='rg',
            field=models.CharField(max_length=9),
        ),
    ]
