# Generated by Django 4.1.7 on 2023-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasapp', '0005_alter_medico_especialidade_alter_medico_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm_medico',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medico',
            name='experiencia',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='doenca_historico_familiar',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='exames_recentes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='frequencia_cardiaca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='frequencia_respiratoria',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medicacoes_em_uso',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressao',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='saturacao',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sintomas',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='temperatura',
            field=models.CharField(max_length=10),
        ),
    ]
